### PR TITLE
#280: Clean up files on failed export

### LINKED ISSUE #280: [BUG] Failing project export can leave empty/incomplete project files
Need to make sure if we handle an exception from the generator that we also clean up any files we may have created during attempted export.

### PR DESCRIPTION
**Pull request by zateutsch**
fixes #280

### CODE REVIEW

File: AIDevGallery/ProjectGenerator/Generator.cs [hunk 1]
```diff
@@ -172,6 +176,7 @@ internal async Task<string> GenerateAsync(Sample sample, Dictionary<ModelType, E
             modelInfos.Add(modelType, new(modelInfo, modelPathStr));
         }
 
+        throw new InvalidOperationException("Sup");
```
Comment (zateutsch) [inline AIDevGallery/ProjectGenerator/Generator.cs]:
```suggestion
```

**Review by nmetulev — APPROVED** [review]
